def build_goal_prompt(categories: list[str]) -> str:
    return (
        "Analyze the user's goal and any provided dates or notes. "
        "Decide if the goal is specific enough to proceed. "
        "Mark is_sufficient = true when the goal includes a measurable target and a clear timeframe. "
        "A clear timeframe is present if the user specifies a duration (e.g., X days/months) "
        "or provides explicit start_date and end_date fields, even if the text does not mention dates. "
        "(for example: save $X by date, lose X kg in Y days, learn skill in Z months, "
        "or explicit start/end dates in the input). "
        "If it is specific, pick exactly one category from the list. "
        "If it is vague or unclear, still pick the best-matching category and provide 1-3 short follow-up questions. "
        "Return ONLY valid JSON with keys: category, is_sufficient, follow_up_questions. "
        "category must be one of the provided categories. "
        "Category guide:\n"
        "- career_and_learning: "
        # Job Search & Career Development
        "job search, job hunting, job applications, applying for jobs, finding employment, changing jobs, "
        "career change, career transition, career switch, switching industries, pivoting careers, "
        "promotions, getting promoted, advancing in career, climbing corporate ladder, career growth, "
        "salary increase, raise negotiation, salary negotiation, compensation negotiation, benefits negotiation, "
        "job offers, evaluating job offers, accepting/declining offers, counter-offers, "
        # Resume & Interview
        "resume building, CV creation, resume optimization, LinkedIn profile, professional profile, "
        "portfolio building, work samples, GitHub profile, personal website, professional branding, "
        "interview preparation, mock interviews, behavioral interviews, technical interviews, coding interviews, "
        "interview practice, interview skills, answering interview questions, STAR method, "
        # Skills & Learning
        "skill development, upskilling, reskilling, learning new skills, technical skills, soft skills, "
        "programming, coding, software development, web development, mobile development, data science, "
        "machine learning, AI, cloud computing, DevOps, cybersecurity, blockchain, "
        "languages (Python, Java, JavaScript, C++, etc.), frameworks, libraries, tools, "
        "certifications, professional certifications, AWS cert, Azure cert, Google cert, PMP, CISSP, "
        "CompTIA, Six Sigma, Scrum Master, product management cert, data analytics cert, "
        "online courses, bootcamps, coding bootcamps, data bootcamps, Coursera, Udemy, edX, "
        "degree programs, bachelor's, master's, MBA, PhD, graduate school, undergrad, "
        # Academic Goals
        "studying, exam preparation, test prep, GRE, GMAT, SAT, ACT, LSAT, MCAT, "
        "improving grades, GPA improvement, academic performance, passing exams, finals, midterms, "
        "thesis, dissertation, research, publications, academic papers, "
        "university applications, college applications, grad school applications, admission essays, "
        "scholarships, financial aid, grants, student loans, "
        "course completion, finishing degree, graduation, completing program, "
        # Professional Development
        "networking, professional networking, attending conferences, industry events, meetups, "
        "mentorship, finding mentor, becoming mentor, coaching, "
        "leadership skills, management skills, team management, project management, people management, "
        "communication skills, presentation skills, public speaking, writing skills, "
        "time management, productivity, organization skills, prioritization, "
        "business skills, entrepreneurship skills, startup skills, product management, "
        # Freelancing & Side Work
        "freelancing, freelance work, side hustle, gig work, contract work, consulting, "
        "building client base, getting freelance clients, pricing services, invoicing, "
        "remote work, work from home, digital nomad, location independence, "
        # Specific Careers & Industries
        "teaching career, becoming teacher, teaching certification, "
        "healthcare career, nursing, medical field, becoming doctor, medical school, "
        "law career, becoming lawyer, law school, bar exam, legal profession, "
        "engineering, software engineering, mechanical engineering, civil engineering, "
        "finance career, accounting, CPA, financial analyst, investment banking, "
        "marketing, digital marketing, social media marketing, content marketing, SEO, "
        "sales, sales skills, closing deals, sales targets, "
        "design, UI/UX design, graphic design, product design, creative work, "
        "trades, electrician, plumber, carpenter, HVAC, construction, "
        "academia, professor, researcher, postdoc, tenure track\n"
        "- fitness: "
        # Weight & Body Composition
        "weight loss, losing weight, fat loss, cutting, shredding, getting lean, "
        "weight gain, gaining weight, bulking, mass gain, muscle building, "
        "body recomposition, body comp, changing body composition, "
        "reaching target weight, ideal weight, healthy weight, BMI goals, "
        "body fat percentage, reducing body fat, lean muscle, "
        # Strength & Muscle
        "muscle gain, building muscle, hypertrophy, getting bigger, getting stronger, "
        "strength training, weightlifting, powerlifting, Olympic lifting, "
        "specific lift goals (bench press, squat, deadlift, overhead press), "
        "progressive overload, strength progression, PR goals (personal records), "
        "bodybuilding, physique goals, muscle definition, vascularity, "
        # Cardio & Endurance
        "cardio, cardiovascular fitness, heart health, aerobic fitness, "
        "running, jogging, sprinting, distance running, trail running, "
        "marathon training, half marathon, 5K, 10K, ultramarathon, "
        "cycling, biking, road cycling, mountain biking, spin classes, "
        "swimming, lap swimming, open water swimming, triathlon, "
        "endurance, stamina, VO2 max, aerobic capacity, "
        # Sports & Athletics
        "athletic performance, sports performance, becoming athlete, "
        "sports training, sport-specific training, "
        "basketball, football, soccer, tennis, golf, baseball, volleyball, "
        "martial arts, boxing, MMA, jiu-jitsu, karate, taekwondo, muay thai, "
        "CrossFit, functional fitness, CrossFit competitions, "
        # Flexibility & Mobility
        "flexibility, stretching, improving flexibility, "
        "yoga, yoga practice, yoga goals, specific poses, advanced yoga, "
        "mobility, joint mobility, range of motion, "
        "splits, doing splits, middle splits, side splits, "
        "touching toes, backbends, handstands, gymnastics moves, "
        # Calisthenics & Bodyweight
        "calisthenics, bodyweight training, bodyweight exercises, "
        "pull-ups, push-ups, dips, muscle-ups, planks, "
        "street workout, bar work, freestyle calisthenics, "
        # Specific Programs & Methods
        "gym workouts, gym routine, training program, workout plan, "
        "HIIT, high intensity interval training, circuit training, "
        "strength programs (5x5, Starting Strength, etc.), "
        "home workouts, working out at home, no equipment workouts, "
        # Diet & Nutrition
        "diet, nutrition, eating healthy, clean eating, "
        "meal planning, meal prep, meal preparation, grocery shopping, "
        "calorie counting, tracking macros, macronutrients, protein intake, "
        "cutting calories, caloric deficit, caloric surplus, "
        "specific diets (keto, paleo, vegan, vegetarian, carnivore, intermittent fasting), "
        "portion control, mindful eating, intuitive eating, "
        "supplements, protein powder, creatine, vitamins, nutrition supplementation, "
        "hydration, drinking water, water intake, "
        # Health & Recovery
        "injury rehabilitation, recovering from injury, physical therapy, "
        "recovery, rest and recovery, active recovery, sleep for fitness, "
        "preventing injury, injury prevention, form correction, "
        "pain management, back pain, knee pain, shoulder pain, "
        # Body Image & Aesthetics
        "body transformation, fitness transformation, before/after, "
        "abs, six-pack abs, core strength, flat stomach, "
        "toned body, defined muscles, looking fit, aesthetic goals, "
        "glutes, building glutes, squat booty, lower body development, "
        "arms, biceps, triceps, shoulder development, chest development, back development, "
        # General Fitness
        "getting fit, general fitness, overall fitness, physical fitness, "
        "starting fitness journey, beginner fitness, fitness for beginners, "
        "staying active, being more active, daily movement, steps goal, "
        "fitness habits, workout consistency, exercise routine, "
        "fitness challenges, 30-day challenge, fitness competition, "
        # Specific Populations
        "postpartum fitness, pregnancy fitness, fitness after baby, "
        "senior fitness, fitness over 50, fitness for older adults, "
        "teen fitness, youth fitness, student fitness, "
        "women's fitness, men's fitness\n"
        "- immigration: "
        # Visa Types - Work
        "work visa, work permit, employment visa, "
        "H1B visa, H1B application, H1B lottery, H1B transfer, H1B extension, H1B stamping, "
        "L1 visa, L1A, L1B, intracompany transfer, "
        "O1 visa, extraordinary ability visa, O1A, O1B, "
        "E2 visa, investor visa, E1 visa, treaty trader, "
        "TN visa, NAFTA visa, Canadian/Mexican professionals, "
        "J1 visa, exchange visitor, J1 waiver, "
        "H2A, H2B, seasonal worker visa, "
        # Visa Types - Student
        "student visa, study visa, study permit, "
        "F1 visa, F1 student visa, F1 OPT, CPT, STEM OPT, "
        "M1 visa, vocational student visa, "
        "J1 student, exchange student visa, "
        "tier 4 visa, UK student visa, "
        "student direct stream, SDS Canada, "
        # Visa Types - Tourist/Visitor
        "tourist visa, visitor visa, B1/B2 visa, "
        "travel visa, vacation visa, visiting family visa, "
        "visa waiver, ESTA, eTA, electronic travel authorization, "
        "transit visa, airport transit visa, "
        "super visa, parent/grandparent visitor visa Canada, "
        # Permanent Residency & Immigration
        "permanent residency, PR, permanent resident, "
        "green card, US green card, employment-based green card, family-based green card, "
        "EB1, EB2, EB3, EB5 green card categories, "
        "diversity visa lottery, DV lottery, green card lottery, "
        "Express Entry Canada, CRS score, provincial nomination, PNP, "
        "skilled worker visa, points-based immigration, "
        "Australia PR, skilled independent visa 189, 190, 491, "
        # Citizenship & Naturalization
        "citizenship, citizenship application, naturalization, "
        "becoming citizen, citizenship test, citizenship ceremony, "
        "dual citizenship, multiple citizenship, "
        "passport application, passport renewal, second passport, "
        # Family-Based Immigration
        "family sponsorship, sponsoring family member, "
        "spouse visa, marriage visa, fiancé visa, K1 visa, CR1/IR1 visa, "
        "parent sponsorship, child sponsorship, sibling sponsorship, "
        "family reunification, "
        # Asylum & Refugee
        "asylum, asylum application, asylum seeker, "
        "refugee status, refugee claim, refugee protection, "
        "humanitarian visa, humanitarian and compassionate grounds, "
        # Country-Specific Immigration
        "immigrating to USA, US immigration, moving to America, "
        "immigrating to Canada, Canadian immigration, moving to Canada, "
        "immigrating to Australia, Australian immigration, moving to Australia, "
        "immigrating to UK, British immigration, moving to United Kingdom, "
        "immigrating to Germany, German immigration, EU immigration, "
        "immigrating to New Zealand, NZ immigration, "
        "Schengen visa, Europe visa, European immigration, "
        # Process & Documentation
        "visa application, visa process, applying for visa, "
        "document preparation, gathering documents, document checklist, "
        "visa interview, consulate interview, embassy interview, interview preparation, "
        "biometrics, visa appointment, visa center, "
        "visa fees, application fees, immigration costs, "
        "visa approval, visa rejection, visa denial, reapplying for visa, "
        "visa extension, extending visa, visa renewal, renewing visa, "
        "change of status, adjusting status, status change, "
        "visa stamping, passport stamping, "
        # Immigration Support
        "immigration lawyer, immigration attorney, legal help, "
        "immigration consultant, registered consultant, RCIC, "
        "affidavit of support, sponsor requirements, financial sponsorship, "
        # Language & Credential Requirements
        "language tests, English proficiency, "
        "IELTS, IELTS preparation, IELTS score, "
        "TOEFL, TOEFL iBT, TOEFL preparation, "
        "PTE, Pearson Test of English, "
        "CELPIP, Canadian English test, "
        "TEF, French language test, TCF, "
        "credential evaluation, educational credential assessment, ECA, "
        "degree equivalency, foreign degree recognition, WES evaluation, "
        # Specific Immigration Programs
        "startup visa, entrepreneur visa, business immigration, "
        "investor immigration, investment migration, "
        "skilled trades immigration, "
        "caregiver program, nanny visa, "
        "agricultural worker program, farm worker visa, "
        # Post-Immigration
        "relocation planning, moving abroad, international move, "
        "settling in new country, integration, adaptation, "
        "finding housing abroad, renting in new country, "
        "opening bank account abroad, international banking, "
        "driver's license abroad, converting license, "
        "health insurance abroad, international health coverage, "
        # Appeals & Complex Cases
        "immigration appeal, appealing visa denial, "
        "deportation defense, removal proceedings, "
        "inadmissibility, waiver application, "
        "overstay, visa overstay, status restoration\n"
        "Examples:\n"
        "# Career and Learning examples\n"
        "- Input: {\"goal_text\":\"Learn Python to get a promotion\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-05-08\"}\n"
        "  Output: {\"category\":\"career_and_learning\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Get AWS Solutions Architect certification by June 2026\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-06-30\"}\n"
        "  Output: {\"category\":\"career_and_learning\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Switch to data science career\",\"start_date\":null,\"end_date\":null}\n"
        "  Output: {\"category\":\"career_and_learning\",\"is_sufficient\":false,\"follow_up_questions\":[\"What skills do you need to learn?\",\"When do you want to make the switch?\",\"Do you have a target company or role?\"]}\n"
        "- Input: {\"goal_text\":\"Improve my GPA to 3.5 by end of semester\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-05-15\"}\n"
        "  Output: {\"category\":\"career_and_learning\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Want to upskill\",\"start_date\":null,\"end_date\":null}\n"
        "  Output: {\"category\":\"career_and_learning\",\"is_sufficient\":false,\"follow_up_questions\":[\"Which skill or technology do you want to learn?\",\"What's your target completion date?\",\"Is this for a job change or promotion?\"]}\n"
        "- Input: {\"goal_text\":\"Get 5 freelance clients\",\"start_date\":null,\"end_date\":null}\n"
        "  Output: {\"category\":\"career_and_learning\",\"is_sufficient\":false,\"follow_up_questions\":[\"By when do you want 5 clients?\",\"What services are you offering?\"]}\n"
        "- Input: {\"goal_text\":\"Complete my MBA by December 2027\",\"start_date\":\"2026-02-08\",\"end_date\":\"2027-12-31\"}\n"
        "  Output: {\"category\":\"career_and_learning\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "# Fitness examples\n"
        "- Input: {\"goal_text\":\"I want to lose 2 kg in 20 days\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-02-27\"}\n"
        "  Output: {\"category\":\"fitness\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Gain 5kg muscle in 3 months\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-05-08\"}\n"
        "  Output: {\"category\":\"fitness\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Run a marathon\",\"start_date\":null,\"end_date\":null}\n"
        "  Output: {\"category\":\"fitness\",\"is_sufficient\":false,\"follow_up_questions\":[\"Which marathon or what date are you targeting?\",\"What's your current running ability?\"]}\n"
        "- Input: {\"goal_text\":\"Get fit\",\"start_date\":null,\"end_date\":null}\n"
        "  Output: {\"category\":\"fitness\",\"is_sufficient\":false,\"follow_up_questions\":[\"What's your specific fitness goal (weight loss, muscle gain, flexibility)?\",\"What's your target timeline?\"]}\n"
        "- Input: {\"goal_text\":\"Bench press 100kg by year end\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-12-31\"}\n"
        "  Output: {\"category\":\"fitness\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Do 20 pull-ups in 2 months\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-04-08\"}\n"
        "  Output: {\"category\":\"fitness\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Become more flexible\",\"start_date\":null,\"end_date\":null}\n"
        "  Output: {\"category\":\"fitness\",\"is_sufficient\":false,\"follow_up_questions\":[\"What's your specific flexibility goal (splits, touch toes, etc.)?\",\"By when do you want to achieve this?\"]}\n"
        "- Input: {\"goal_text\":\"Complete a triathlon in 6 months\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-08-08\"}\n"
        "  Output: {\"category\":\"fitness\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "# Immigration examples\n"
        "- Input: {\"goal_text\":\"Apply for a student visa for Australia\",\"start_date\":\"2026-03-01\",\"end_date\":\"2026-06-01\"}\n"
        "  Output: {\"category\":\"immigration\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Get Canadian PR by December 2026\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-12-31\"}\n"
        "  Output: {\"category\":\"immigration\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Move abroad\",\"start_date\":null,\"end_date\":null}\n"
        "  Output: {\"category\":\"immigration\",\"is_sufficient\":false,\"follow_up_questions\":[\"Which country are you targeting?\",\"What type of visa (work, study, PR)?\",\"What's your timeline?\"]}\n"
        "- Input: {\"goal_text\":\"Get H1B visa\",\"start_date\":null,\"end_date\":null}\n"
        "  Output: {\"category\":\"immigration\",\"is_sufficient\":false,\"follow_up_questions\":[\"When do you plan to apply?\",\"Do you have a sponsor/employer?\"]}\n"
        "- Input: {\"goal_text\":\"Apply for US green card through EB2 by March 2026\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-03-31\"}\n"
        "  Output: {\"category\":\"immigration\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        "- Input: {\"goal_text\":\"Score 7.5 in IELTS for Canada PR\",\"start_date\":null,\"end_date\":null}\n"
        "  Output: {\"category\":\"immigration\",\"is_sufficient\":false,\"follow_up_questions\":[\"When do you plan to take the IELTS test?\",\"When do you want to submit your PR application?\"]}\n"
        "- Input: {\"goal_text\":\"Extend my F1 visa before it expires in May\",\"start_date\":\"2026-02-08\",\"end_date\":\"2026-05-01\"}\n"
        "  Output: {\"category\":\"immigration\",\"is_sufficient\":true,\"follow_up_questions\":[]}\n"
        f"Available categories: {', '.join(categories)}."
    )
